### ISSUE TITLE
FPC (Without Lazarus) Demo?

### ISSUE THREAD

**Issue by Zaaphod** [LongDirtyAnimAlf/FPC-USB-HID#2]
Is it possible to get a simple demo that works Windows with just FPC and does not require Lazarus?  Or is Lazarus required for this to work?

I am trying to access a USB device with a FreePascal Console application written in FPC3.0.4   I don't have Lazarus or even know how Lazarus works.

**Comment by LongDirtyAnimAlf** [comment]
Will look into this next week.
Stay tuned.

**Comment by LongDirtyAnimAlf** [comment]
I have added a small Windows only console app.
