### ISSUE TITLE
Errors Compiling with Lazarus

### ISSUE THREAD

**Issue by DaveCoventry** [LongDirtyAnimAlf/FPC-USB-HID#3]
The following errors were raised compiling.

`usbcontroller.pas(313,5) Warning: (3018) Constructor should be public
usbcontroller.pas(377,5) Warning: (3018) Constructor should be public
usbcontroller.pas(684,3) Note: (5027) Local variable "Action" is assigned but never used
usbcontroller.pas(910,3) Note: (6058) Call to subroutine "function FpWrite(fd:LongInt;const buf:<Formal type>;nbytes:QWord):Int64;" marked as inline is not inlined
usbcontroller.pas(1258,5) Note: (5027) Local variable "LocalHidNode" is assigned but never used
usbcontroller.pas(1258,18) Note: (5027) Local variable "LocalInterfaceNode" is assigned but never used
usbcontroller.pas(1576,62) Warning: (2005) Comment level 2 found
usbcontroller.pas(320,29) Hint: (5024) Parameter "CreateSuspended" not used
usbcontroller.pas(1628,15) Note: (6058) Call to subroutine "function FpRead(fd:LongInt;var buf:<Formal type>;nbytes:QWord):Int64;" marked as inline is not inlined
usbcontroller.pas(2110,14) Note: (6058) Call to subroutine "function FpRead(fd:LongInt;var buf:<Formal type>;nbytes:QWord):Int64;" marked as inline is not inlined
usbcontroller.pas(2181,6) Note: (5027) Local variable "lo" is assigned but never used
usb2.pas(34,26) Hint: (5024) Parameter "HidDev" not used
usb2.pas(34,84) Hint: (5024) Parameter "Size" not used
usb2.pas(210,10) Error: (5038) identifier idents no member "OnEnumerate"
usb2.pas(210,38) Error: (3026) Wrong number of parameters specified for call to "HidCtlEnumerate"
usb2.pas(68,14) Error: (5088) Found declaration: HidCtlEnumerate(TJvHidDevice;const LongInt):Boolean;
usb2.pas(222,10) Error: (5038) identifier idents no member "OnEnumerate"
usb2.pas(257,42) Error: (3026) Wrong number of parameters specified for call to "DeviceChange"
usb2.pas(80,15) Error: (5088) Found declaration: DeviceChange(TObject);
usb2.pas(293,18) Error: (5038) identifier idents no member "Enumerate"
usb2.pas(317,105) Hint: (5057) Local variable "Written" does not seem to be initialized
usb2.pas(663) Fatal: (10026) There were 7 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
`
Lazarus 2.0.10 rUnversioned directory FPC 3.2.0 x86_64-linux-gtk2

~ Dave

**Comment by LongDirtyAnimAlf** [comment]
Confirmed.
Should be fixed by latest release.
Please test. Thanks.

**Comment by LongDirtyAnimAlf** [comment]
No feedback.
