### ISSUE TITLE
range check error while evaluating constant

### ISSUE THREAD

**Issue by Lulu04** [LongDirtyAnimAlf/FPC-USB-HID#4]
Hi sir, thanks tou for sharing this code ! I use it under windows and it work well. I'm a newbi in usb and your code help me a lot.
I try to adapt my project to Linux but I can't compile it :
in unit 'usbcontroller.pas' the compiler complains **range check error while evaluating constant** on each call of function fpioctl()
I use Lazarus 2.0.10, FPC 3.2.0
I try to change the declaration of constant HIDIOCGSTRING and other but without succes.
Any idea ?

**Comment by LongDirtyAnimAlf** [comment]
I cannot reproduce this error unfortunately.
You are on Linux ? Or Mac. Or BSD ?

**Comment by Lulu04** [comment]
My machine is win10 and I use VirtualBox to test my application under Ubuntu Mate 20

**Comment by LongDirtyAnimAlf** [comment]
If still valid, would you mind testing the latest sources ?
I tried to solve this siiue.

**Comment by Lulu04** [comment]
Hi, sorry I just read your reply.
Yes, now it compile without error. Tested under Win10 64b,  and Linux 64 and 32b.
Thanks you !
Regards
