### ISSUE TITLE
Crash when the device is removed before fully connecting (with patch).

### ISSUE THREAD

**Issue by oldmanruss** [LongDirtyAnimAlf/FPC-USB-HID#5]
If a device is plugged in and then removed before fully connecting, a range check error is raised in procedure TJvHidDeviceReadThread.Execute() in JvHidControllerClass.pas, which causes the application to crash.

The attached patch solves the issue, but I'm sure there is a better way to do it.

Tested on windows 10, both 32bit and 64 bit targets.

[JvHidControllerClass.pas.patch.txt](https://github.com/LongDirtyAnimAlf/FPC-USB-HID/files/9844104/JvHidControllerClass.pas.patch.txt)

**Comment by LongDirtyAnimAlf** [comment]
Thanks for this report. Just a (few) question(s).

In your patch, you do: "if ReportLen = 0 then break;" This will result in the execute loop to be terminated with boolean "Terminated" still false. This will break the thread logic.
So, I wonder. There might be another flag that could be used when this error happens.
E.g. IsCheckedOut or IsPluggedIn. Would you mind checking the values of these to properties when the range check error occurs ? It might be better to terminate the read thread using one of these.

And.

Does a OnUnplug event occur in this error case ?

Thanks for your help !

**Comment by oldmanruss** [comment]
IsCheckedOut is always true.
Most of the time IsPluggedIn is also true, in which case the OnUnplug event is called.

The behavior in debug and release modes is different: In debug mode two errors are actually reported, first a range check error on the FillChar statement and then an ERangeError. If the errors are "ignored" in the project options, the program continues. In release mode, an unknown exception code $C000041D is raised and the program crashes.

There appears to be a bug in Fillchar in that a count of 0 shouldn't raise an error, so I tried two things:
`      if ReportLen > 0 then
        FillChar(Report[0], ReportLen, #0); 
`
and 
`
      {$push} {$rangechecks off}
      FillChar(Report[0], ReportLen, #0);
      {$pop}           
`

These both appear to work, but DeviceReadFileEx() is called about 10 times, each time returning false and causing the else if (not Terminated) error reporting clause to be invoked. The DoUnplug event is not always called and windows sometimes complains about unrecognized USB devices.

One time this caused my mouse to stop responding - until I unplugged the mouse's wireless dongle and then the DoUnplug event was called multiple times.

By the way the thanks is all mine, for all the work you do on this and and on fpcupdeluxe.

**Comment by oldmanruss** [comment]
OK, I didn't realize that Report[] was a dynamic array. When I tried to reproduce the range check error in a simple command line program no error is raised. This is with FPC 3.2.2

In addition this I see this on my old slow Core-I5 laptop, but not on my desktop running the same program. The code returned by GetLastError in TJvHidDeviceReadThread.Execute on the laptop is ERROR_DEVICE_NOT_CONNECTED while the on the desktop it returns 0. This is perhaps a timing issue and will be hard to reproduce.

Also on the laptop, sometimes in TJvHidDevice.CtlCreate a Device Cannot Be Identified error is raised. I see in your latest version that Device Cannot Be Opened is commented out. Do you think this could be commented out?

**Comment by LongDirtyAnimAlf** [comment]
Please try then latest sources. These new sources might work better.
And, if not, we will try other things.

**Comment by oldmanruss** [comment]
I still very occasionally get  unknown exception code $C000041D which when I look at the call stack comes from `raise EControllerError.CreateRes(@RsEDeviceCannotBeIdentified);` in JvHidDevice.CtlCreate, but it is so infrequent and in any event rapidly plugging in and removing the device is not normal operation.

I apologize for the noise and thank you for your help.

**Comment by LongDirtyAnimAlf** [comment]
Thanks. And you're welcome.
I will live this exception untouched, as it comes from a known place and a known situation.
