### ISSUE TITLE
Invalid TSPDeviceInterfaceDetailData record size in 64-bit fpc 

### ISSUE THREAD

**Issue by Eugene-Kovalsky** [LongDirtyAnimAlf/FPC-USB-HID#6]
The examples do not work when compiled to 64-bit under Windows. The reason is that SizeOf() returns an invalid value for the size of the TSPDeviceInterfaceDetailData record (returns 7).  The correct value (8) will be returned if the _packed_ keyword is removed from the record declaration. It looks like the declaration {$PACKRECORDS 8} in JvSetupApi.pas is not working.

**Comment by LongDirtyAnimAlf** [comment]
Tried to solve.
Please test.

**Comment by Eugene-Kovalsky** [comment]
Thanks a lot for the corrections! Now the examples work fine.
